package main;

import java.awt.Image;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.UIManager;

/**
 *
 * @author tranh
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        initGameWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerChat = new javax.swing.JTextField();
        OK = new javax.swing.JButton();
        gameLog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Number Guess V1.0");

        playerChat.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        playerChat.setEnabled(false);

        OK.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        gameLog.setBackground(new java.awt.Color(255, 255, 255));
        gameLog.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerChat, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameLog, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playerChat)
                    .addComponent(OK, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        boolean isValidNumber = false;
        if (isFirstTime == true) {
            gameLog.setText("Number you need to guess in range 0 to 100");
            playerChat.setEnabled(true);
            isFirstTime = false;
        } else {
            try {
                num = Integer.parseInt(playerChat.getText());
                if (num < 0) {
                    gameLog.setText("You can not input a negative number!");
                } else {
                    isValidNumber = true;
                }
            } catch (NumberFormatException e) {
                gameLog.setText("Please enter a number in range 0 to 100!");
                isValidNumber = false;
            }
            playerChat.setText("");
            if (isValidNumber == true) {
                gameController(numberToFind, num);
            }
        }
    }//GEN-LAST:event_OKActionPerformed

    boolean isFirstTime = true;
    int numberToFind = -1;
    int num = 0;

    private void initGameWindow() {
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        Image image;
        try {
            image = ImageIO.read(getClass().getResource("/img/logo.png"));
            this.setIconImage(image);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        generateNumber(100);
        gameLog.setText("<html>WELCOME TO NUMBER GUESS GAME V1.0"
                + "<br>Create by: github.com/trhiep"
                + "<br>Click OK to start game!"
                + "</html>");
    }

    private void gameController(int numberToFind, int num) {
        if (numberToFind == num) {
            generateNumber(100);
            gameLog.setText("<html>Congratulations! You won!"
                    + "<br>Click OK to start a new game!</html>");
            playerChat.setEnabled(false);
            isFirstTime = true;
        } else if (numberToFind < num) {
            gameLog.setText("Number you need to guess is smaller than " + num + ".");
        } else if (numberToFind > num) {
            gameLog.setText("Number you need to guess is greater than " + num + ".");
        }
    }

    private void generateNumber(int range) {
        Random rand = new Random();
        numberToFind = rand.nextInt(range);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new Main().setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK;
    private javax.swing.JLabel gameLog;
    private javax.swing.JTextField playerChat;
    // End of variables declaration//GEN-END:variables
}
